package com.hxkj.common.config;

import com.hxkj.bus.model.BusNovel;
import com.hxkj.bus.model.BusNovelChapter;
import com.hxkj.system.model.*;
import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class MappingKit {


    public static void mapping(ActiveRecordPlugin arp) {

        arp.addMapping("sys_menu", "id", SysMenu.class);
        arp.addMapping("sys_oplog", "id", SysOplog.class);
        arp.addMapping("sys_org", "id", SysOrg.class);
        arp.addMapping("sys_role", "id", SysRole.class);
        // Composite Primary Key order: menu_id,role_id
        arp.addMapping("sys_role_menu", "menu_id,role_id", SysRoleMenu.class);
        arp.addMapping("sys_user", "id", SysUser.class);
        // Composite Primary Key order: role_id,user_id
        arp.addMapping("sys_user_role", "role_id,user_id", SysUserRole.class);
        arp.addMapping("sys_task", "id", SysTask.class);
        arp.addMapping("sys_task_log", "id", SysTaskLog.class);
        arp.addMapping("sys_dict", "id", SysDict.class);
        arp.addMapping("sys_file", "id", SysFile.class);
        arp.addMapping("sys_code", "id", SysCode.class);


        arp.addMapping("bus_novel", "id", BusNovel.class);
        arp.addMapping("bus_novel_chapter", "id", BusNovelChapter.class);
    }
}

