package com.hxkj.system.model;

import com.hxkj.system.model.base.BaseSysMenu;

import java.util.List;

/**
 * Generated by JFinal.
 * 菜单
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {
    public static final SysMenu dao = new SysMenu().dao();

    public List<SysMenu> findAll() {
        String sql = "select * from sys_menu order by  sort asc";
        return find(sql);
    }

    public List<SysMenu> getChildren() {
        return get("children");
    }
}
