package com.hxkj.system.model;


import com.hxkj.system.model.base.BaseSysOplog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOplog extends BaseSysOplog<SysOplog> {
	public static final SysOplog dao = new SysOplog().dao();
}
