package com.hxkj.system.model;

import com.hxkj.system.model.base.BaseSysOrg;
import com.jfinal.kit.StrKit;

import java.util.List;

/**
 * Generated by JFinal.
 * 部门
 */
@SuppressWarnings("serial")
public class SysOrg extends BaseSysOrg<SysOrg> {
    public static final SysOrg dao = new SysOrg().dao();

    public List<SysOrg> findWhere(String where) {
        String sqlSelect = " select * ";
        String sqlExceptSelect = " from sys_org  ";
        if (StrKit.notBlank(where)) {
            sqlExceptSelect += " where " + where;
        }
        sqlExceptSelect += " order by   sort asc ";
        List<SysOrg> sysOrgs = SysOrg.dao.find(sqlSelect + sqlExceptSelect);
        return sysOrgs;
    }
}
