package com.hxkj.system.model;


import com.hxkj.system.model.base.BaseSysOplog;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOplog extends BaseSysOplog<SysOplog> {
    public static final SysOplog dao = new SysOplog().dao();

    public Page<SysOplog> page(int pageNumber, int pageSize, String where) {
        String sqlSelect = " select so.*, su.name as user_name ";
        String sqlExceptSelect = " from sys_oplog  so LEFT JOIN sys_user  su on so.user_id = su.id  ";
        if (StrKit.notBlank(where)) {
            sqlExceptSelect += " where " + where;
        }
        sqlExceptSelect += " order by so.create_time desc ";
        Page<SysOplog> sysOplogPage = SysOplog.dao.paginate(pageNumber, pageSize, sqlSelect, sqlExceptSelect);
        return sysOplogPage;
    }

    public List<SysOplog> findWhere(String where) {
        String sqlSelect = " select so.*, su.name as user_name ";
        String sqlExceptSelect = " from sys_oplog  so LEFT JOIN sys_user  su on so.user_id = su.id  ";
        if (StrKit.notBlank(where)) {
            sqlExceptSelect += " where " + where;
        }

        sqlExceptSelect += "order by so.create_time desc";
        List<SysOplog> sysOplogs = SysOplog.dao.find(sqlSelect + sqlExceptSelect);
        return sysOplogs;
    }

}
