package com.hxkj.system.model;

import com.hxkj.system.model.base.BaseSysOrg;

import java.util.List;

/**
 * Generated by JFinal.
 * 部门
 */
@SuppressWarnings("serial")
public class SysOrg extends BaseSysOrg<SysOrg> {
    public static final SysOrg dao = new SysOrg().dao();

    public List<SysOrg> findAll() {
        String sql = "select * from sys_org order by  sort asc";
        return find(sql);
    }

    public List<SysOrg> getChildren() {
        return get("children");
    }
}
