package com.hxkj.system.model;

import com.hxkj.system.model.base.BaseSysRoleMenu;

import java.util.List;

/**
 * Generated by JFinal.
 * 角色 菜单表
 */
@SuppressWarnings("serial")
public class SysRoleMenu extends BaseSysRoleMenu<SysRoleMenu> {
    public static final SysRoleMenu dao = new SysRoleMenu().dao();

    public List<SysRoleMenu> findByRoleId(Integer roleId) {
        String sql = "select * from sys_role_menu where role_id = ? ";
        return find(sql, roleId);
    }
}
