package com.hxkj.system.model;

import com.hxkj.system.model.base.BaseSysRole;

import java.util.List;

/**
 * Generated by JFinal.
 * 角色
 */
@SuppressWarnings("serial")
public class SysRole extends BaseSysRole<SysRole> {
	public static final SysRole dao = new SysRole().dao();

	public List<SysRole> findAll(){
		String sql = "select * from sys_role order by sort";
		return find(sql);
	}
}
