package com.hxkj.system.model;


import com.hxkj.system.model.base.BaseSysTask;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysTask extends BaseSysTask<SysTask> {
    public static final SysTask dao = new SysTask().dao();

    public String getTaskType() {
        return get("task_type");
    }

    public String getTaskStatus() {
        return get("task_status");
    }

}
