package com.hxkj.system.model;


import com.hxkj.system.model.base.BaseSysTaskLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysTaskLog extends BaseSysTaskLog<SysTaskLog> {
    public static final SysTaskLog dao = new SysTaskLog().dao();
}
