package com.hxkj.system.model;

import com.hxkj.system.model.base.BaseSysUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserRole extends BaseSysUserRole<SysUserRole> {
	public static final SysUserRole dao = new SysUserRole().dao();
}
