package com.hxkj.bus.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by com.hxkj.common.util.generator.MyGenerator
 */
@SuppressWarnings("serial")
public abstract class BaseBusNovelChapter<M extends BaseBusNovelChapter<M>> extends Model<M> implements IBean {

    public void setId(String id) {
        set("id", id);
    }

    public String getId() {
        return get("id");
    }

    public void setTitle(String title) {
        set("title", title);
    }

    public String getTitle() {
        return get("title");
    }

    public void setContent(String content) {
        set("content", content);
    }

    public String getContent() {
        return get("content");
    }

}
