package com.hxkj.bus.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by com.hxkj.common.util.generator.MyGenerator
 */
@SuppressWarnings("serial")
public abstract class BaseBusTwoPk<M extends BaseBusTwoPk<M>> extends Model<M> implements IBean {

    public String getId() {
        return get("id");
    }

    public void setId(String id) {
        set("id", id);
    }

    public String getId2() {
        return get("id2");
    }

    public void setId2(String id2) {
        set("id2", id2);
    }

    public String getV() {
        return get("v");
    }

    public void setV(String v) {
        set("v", v);
    }

}
