package com.hxkj.bus.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
* Generated by com.hxkj.common.util.generator.MyGenerator
*/
@SuppressWarnings("serial")
public abstract class BaseBusNovel<M extends BaseBusNovel<M>> extends Model<M> implements IBean {

           public void setId(String id) {
               set("id", id);
           }

           public String getId() {
               return get("id");
           }

           public void setTitle(String title) {
               set("title", title);
           }

           public String getTitle() {
               return get("title");
           }

           public void setAuthor(String author) {
               set("author", author);
           }

           public String getAuthor() {
               return get("author");
           }

           public void setCreateTime(java.util.Date createTime) {
               set("create_time", createTime);
           }

           public java.util.Date getCreateTime() {
               return get("create_time");
           }

}
