package com.hxkj.system.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysOplog<M extends BaseSysOplog<M>> extends Model<M> implements IBean {

    public String getId() {
        return get("id");
    }

    public void setId(String id) {
        set("id", id);
    }

    public String getUserId() {
        return get("user_id");
    }

    public void setUserId(String userId) {
        set("user_id", userId);
    }

    public String getOpContent() {
        return get("op_content");
    }

    public void setOpContent(String opContent) {
        set("op_content", opContent);
    }

    public String getIp() {
        return get("ip");
    }

    public void setIp(String ip) {
        set("ip", ip);
    }

    public java.util.Date getCreateTime() {
        return get("create_time");
    }

    public void setCreateTime(java.util.Date createTime) {
        set("create_time", createTime);
    }

}
