package com.hxkj.system.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysTask<M extends BaseSysTask<M>> extends Model<M> implements IBean {

    public Integer getId() {
        return get("id");
    }

    public void setId(Integer id) {
        set("id", id);
    }

    public String getName() {
        return get("name");
    }

    public void setName(String name) {
        set("name", name);
    }

    public Integer getTargetType() {
        return get("target_type");
    }

    public void setTargetType(Integer targetType) {
        set("target_type", targetType);
    }

    public String getTargetValue() {
        return get("target_value");
    }

    public void setTargetValue(String targetValue) {
        set("target_value", targetValue);
    }

    public String getCron() {
        return get("cron");
    }

    public void setCron(String cron) {
        set("cron", cron);
    }

    public String getLastRunResult() {
        return get("last_run_result");
    }

    public void setLastRunResult(String lastRunResult) {
        set("last_run_result", lastRunResult);
    }

    public java.util.Date getLastRunTime() {
        return get("last_run_time");
    }

    public void setLastRunTime(java.util.Date lastRunTime) {
        set("last_run_time", lastRunTime);
    }

    public Integer getLastRunTimeCost() {
        return get("last_run_time_cost");
    }

    public void setLastRunTimeCost(Integer lastRunTimeCost) {
        set("last_run_time_cost", lastRunTimeCost);
    }

    public Integer getStatus() {
        return get("status");
    }

    public void setStatus(Integer status) {
        set("status", status);
    }

    public Integer getCreateUserId() {
        return get("create_user_id");
    }

    public void setCreateUserId(Integer createUserId) {
        set("create_user_id", createUserId);
    }

    public java.util.Date getCreateTime() {
        return get("create_time");
    }

    public void setCreateTime(java.util.Date createTime) {
        set("create_time", createTime);
    }

}
