package com.hxkj.system.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysOrg<M extends BaseSysOrg<M>> extends Model<M> implements IBean {

    public Integer getId() {
        return get("id");
    }

    public void setId(Integer id) {
        set("id", id);
    }

    public String getOrgName() {
        return get("org_name");
    }

    public void setOrgName(String orgName) {
        set("org_name", orgName);
    }

    public String getOrgAddress() {
        return get("org_address");
    }

    public void setOrgAddress(String orgName) {
        set("org_address", orgName);
    }

    public String getOrgRemark() {
        return get("org_remark");
    }

    public void setOrgRemark(String orgName) {
        set("org_remark", orgName);
    }

    public Integer getSort() {
        return get("sort");
    }

    public void setSort(Integer sort) {
        set("sort", sort);
    }

    public Integer getPid() {
        return get("pid");
    }

    public void setPid(Integer pid) {
        set("pid", pid);
    }


}
