package com.hxkj.system.model.base;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysMenu<M extends BaseSysMenu<M>> extends Model<M> implements IBean {

    public Integer getId() {
        return get("id");
    }

    public void setId(Integer id) {
        set("id", id);
    }

    public String getName() {
        return get("name");
    }

    public void setName(String name) {
        set("name", name);
    }

    @JSONField(ordinal = 3)
    public String getUrl() {
        return get("url");
    }

    public void setUrl(String url) {
        set("url", url);
    }

    public String getIcon() {
        return get("icon");
    }

    public void setIcon(String icon) {
        set("icon", icon);
    }

    public String getIconfont() {
        return get("iconfont");
    }

    public void setIconfont(String icon) {
        set("iconfont", icon);
    }

    public Integer getSort() {
        return get("sort");
    }

    public void setSort(Integer sort) {
        set("sort", sort);
    }

    public Integer getPid() {
        return get("pid");
    }

    public void setPid(Integer pid) {
        set("pid", pid);
    }

}
