package com.hxkj.system.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by com.hxkj.common.util.generator.MyGenerator
 */
@SuppressWarnings("serial")
public abstract class BaseSysFile<M extends BaseSysFile<M>> extends Model<M> implements IBean {

    public Integer getId() {
        return get("id");
    }

    public void setId(Integer id) {
        set("id", id);
    }

    public String getUserId() {
        return get("user_id");
    }

    public void setUserId(String userId) {
        set("user_id", userId);
    }

    public String getPath() {
        return get("path");
    }

    public void setPath(String path) {
        set("path", path);
    }

    public String getOriginalFilename() {
        return get("original_filename");
    }

    public void setOriginalFilename(String originalFilename) {
        set("original_filename", originalFilename);
    }

    public String getType() {
        return get("type");
    }

    public void setType(String type) {
        set("type", type);
    }

    public String getRemark() {
        return get("remark");
    }

    public void setRemark(String remark) {
        set("remark", remark);
    }

    public java.util.Date getCreateTime() {
        return get("create_time");
    }

    public void setCreateTime(java.util.Date createTime) {
        set("create_time", createTime);
    }

}
