package com.hxkj.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysTask<M extends BaseSysTask<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setTargetType(Integer targetType) {
		set("target_type", targetType);
	}

	public Integer getTargetType() {
		return get("target_type");
	}

	public void setTargetValue(String targetValue) {
		set("target_value", targetValue);
	}

	public String getTargetValue() {
		return get("target_value");
	}

	public void setCron(String cron) {
		set("cron", cron);
	}

	public String getCron() {
		return get("cron");
	}

	public void setLastRunResult(String lastRunResult) {
		set("last_run_result", lastRunResult);
	}

	public String getLastRunResult() {
		return get("last_run_result");
	}

	public void setLastRunTime(java.util.Date lastRunTime) {
		set("last_run_time", lastRunTime);
	}

	public java.util.Date getLastRunTime() {
		return get("last_run_time");
	}

	public void setLastRunTimeCost(Integer lastRunTimeCost) {
		set("last_run_time_cost", lastRunTimeCost);
	}

	public Integer getLastRunTimeCost() {
		return get("last_run_time_cost");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
	}

	public Integer getCreateUserId() {
		return get("create_user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
