package com.hxkj.system.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
* Generated by com.hxkj.common.util.generator.MyGenerator
*/
@SuppressWarnings("serial")
public abstract class BaseSysCode<M extends BaseSysCode<M>> extends Model<M> implements IBean {

           public void setId(Integer id) {
               set("id", id);
           }

           public Integer getId() {
               return get("id");
           }

           public void setType(String type) {
               set("type", type);
           }

           public String getType() {
               return get("type");
           }

           public void setTypeDesc(String typeDesc) {
               set("type_desc", typeDesc);
           }

           public String getTypeDesc() {
               return get("type_desc");
           }

           public void setCode(String code) {
               set("code", code);
           }

           public String getCode() {
               return get("code");
           }

           public void setSort(Integer sort) {
               set("sort", sort);
           }

           public Integer getSort() {
               return get("sort");
           }

           public void setCreateTime(java.util.Date createTime) {
               set("create_time", createTime);
           }

           public java.util.Date getCreateTime() {
               return get("create_time");
           }

}
