package com.hxkj.system.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysDict<M extends BaseSysDict<M>> extends Model<M> implements IBean {

    public Integer getId() {
        return get("id");
    }

    public void setId(Integer id) {
        set("id", id);
    }

    public String getDictType() {
        return get("dict_type");
    }

    public void setDictType(String dictType) {
        set("dict_type", dictType);
    }

    public String getDictKey() {
        return get("dict_key");
    }

    public void setDictKey(String dictKey) {
        set("dict_key", dictKey);
    }

    public String getDictValue() {
        return get("dict_value");
    }

    public void setDictValue(String dictValue) {
        set("dict_value", dictValue);
    }

    public java.util.Date getCreateTime() {
        return get("create_time");
    }

    public void setCreateTime(java.util.Date createTime) {
        set("create_time", createTime);
    }

}
