package com.hxkj.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysMenu<M extends BaseSysMenu<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

 
	public Integer getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

 
	public String getName() {
		return get("name");
	}

	
	
	public void setUrl(String url) {
		set("url", url);
	}

	@JSONField(ordinal=3)
	public String getUrl() {
		return get("url");
	}

	public void setIcon(String icon) {
		set("icon", icon);
	}

	public String getIcon() {
		return get("icon");
	}

	public void setSort(Integer sort) {
		set("sort", sort);
	}

	public Integer getSort() {
		return get("sort");
	}

	public void setPid(Integer pid) {
		set("pid", pid);
	}

	public Integer getPid() {
		return get("pid");
	}

}
